// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

interface FooterDocumentData {}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *header → Navbar*
 */
export interface HeaderDocumentDataNavbarItem {
  /**
   * Link field in *header → Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navbar[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *header → service sub menu*
 */
export interface HeaderDocumentDataServiceSubMenuItem {
  /**
   * Link field in *header → service sub menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.service_sub_menu[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type HeaderDocumentDataSlicesSlice = never;

/**
 * Content for header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navbar field in *header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navbar[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navbar: prismic.GroupField<Simplify<HeaderDocumentDataNavbarItem>>;

  /**
   * service sub menu field in *header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.service_sub_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  service_sub_menu: prismic.GroupField<
    Simplify<HeaderDocumentDataServiceSubMenuItem>
  >;

  /**
   * `slices` field in *header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | InformationObligationsSlice
  | IndustrialCaeSlice
  | DisclaimerSlice
  | FooterTixasSlice
  | TermAndCondtionSlice
  | PrivacyPolicySlice
  | FaqSlice
  | AutomotiveServicesSlice
  | CaeServiceSlice
  | CooperateLinkSlice
  | PartnersSlice
  | LocationSlice
  | EngineeringServiceSlice
  | VacenciesSlice
  | TopNavbarSlice
  | TeamSlice
  | ServicesSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *settings → Footer link*
 */
export interface SettingsDocumentDataFooterLinkItem {
  /**
   * link field in *settings → Footer link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_link[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *settings → Footer Icon*
 */
export interface SettingsDocumentDataFooterIconItem {
  /**
   * link field in *settings → Footer Icon*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *settings → Footer Icon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;
}

type SettingsDocumentDataSlicesSlice = TopNavbarSlice;

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * site title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * site description field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_description: prismic.KeyTextField;

  /**
   * OG Image field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Footer logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Footer link field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_link: prismic.GroupField<Simplify<SettingsDocumentDataFooterLinkItem>>;

  /**
   * Footer Icon field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_icon: prismic.GroupField<Simplify<SettingsDocumentDataFooterIconItem>>;

  /**
   * Slice Zone field in *settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *PageServices → PageServices → Primary → card*
 */
export interface AutomotiveServicesSliceDefaultPrimaryCardItem {
  /**
   * card image field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card heading field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card sub heading field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[].card_sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_sub_heading: prismic.RichTextField;

  /**
   * card popup detail field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[].card_popup_detail
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_popup_detail: prismic.RichTextField;

  /**
   * card popup heading field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[].card_popup_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_popup_heading: prismic.RichTextField;

  /**
   * card link field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[].card_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * card popup background field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[].card_popup_background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_popup_background: prismic.ImageField<never>;

  /**
   * popup field in *PageServices → PageServices → Primary → card*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: automotive_services.default.primary.card[].popup
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  popup: prismic.BooleanField;
}

/**
 * Primary content in *PageServices → PageServices → Primary*
 */
export interface AutomotiveServicesSliceDefaultPrimary {
  /**
   * content field in *PageServices → PageServices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * card field in *PageServices → PageServices → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<
    Simplify<AutomotiveServicesSliceDefaultPrimaryCardItem>
  >;

  /**
   * Background Image field in *PageServices → PageServices → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * heading field in *PageServices → PageServices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * sub heading field in *PageServices → PageServices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: automotive_services.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;
}

/**
 * PageServices variation for PageServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AutomotiveServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AutomotiveServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageServices*
 */
type AutomotiveServicesSliceVariation = AutomotiveServicesSliceDefault;

/**
 * PageServices Shared Slice
 *
 * - **API ID**: `automotive_services`
 * - **Description**: AutomotiveServices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AutomotiveServicesSlice = prismic.SharedSlice<
  "automotive_services",
  AutomotiveServicesSliceVariation
>;

/**
 * Item in *CaeService → Default → Primary → card*
 */
export interface CaeServiceSliceDefaultPrimaryCardItem {
  /**
   * card image field in *CaeService → Default → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cae_service.default.primary.card[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card heading field in *CaeService → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cae_service.default.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card link field in *CaeService → Default → Primary → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cae_service.default.primary.card[].card_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * card points field in *CaeService → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cae_service.default.primary.card[].card_points
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_points: prismic.RichTextField;
}

/**
 * Primary content in *CaeService → Default → Primary*
 */
export interface CaeServiceSliceDefaultPrimary {
  /**
   * heading field in *CaeService → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cae_service.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * card field in *CaeService → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cae_service.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<CaeServiceSliceDefaultPrimaryCardItem>>;

  /**
   * Background Image field in *CaeService → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cae_service.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for CaeService Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaeServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaeServiceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CaeService*
 */
type CaeServiceSliceVariation = CaeServiceSliceDefault;

/**
 * CaeService Shared Slice
 *
 * - **API ID**: `cae_service`
 * - **Description**: CaeService
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaeServiceSlice = prismic.SharedSlice<
  "cae_service",
  CaeServiceSliceVariation
>;

/**
 * Item in *CooperateLink → Default → Primary → Cooperate links*
 */
export interface CooperateLinkSliceDefaultPrimaryCooperateLinksItem {
  /**
   * title field in *CooperateLink → Default → Primary → Cooperate links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * link field in *CooperateLink → Default → Primary → Cooperate links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon field in *CooperateLink → Default → Primary → Cooperate links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;
}

/**
 * Primary content in *CooperateLink → Default → Primary*
 */
export interface CooperateLinkSliceDefaultPrimary {
  /**
   * Heading field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_headeing: prismic.RichTextField;

  /**
   * Contact field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.contact
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact: prismic.RichTextField;

  /**
   * Cooperate links field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cooperate_links: prismic.GroupField<
    Simplify<CooperateLinkSliceDefaultPrimaryCooperateLinksItem>
  >;
}

/**
 * Default variation for CooperateLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CooperateLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CooperateLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CooperateLink*
 */
type CooperateLinkSliceVariation = CooperateLinkSliceDefault;

/**
 * CooperateLink Shared Slice
 *
 * - **API ID**: `cooperate_link`
 * - **Description**: CooperateLink
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CooperateLinkSlice = prismic.SharedSlice<
  "cooperate_link",
  CooperateLinkSliceVariation
>;

/**
 * Item in *Disclaimer → Default → Primary → Non Repeated*
 */
export interface DisclaimerSliceDefaultPrimaryNonRepeatedItem {
  /**
   * heading field in *Disclaimer → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.non_repeated[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * contant field in *Disclaimer → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.non_repeated[].contant
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contant: prismic.RichTextField;
}

/**
 * Item in *Disclaimer → Default → Primary → Repeatable*
 */
export interface DisclaimerSliceDefaultPrimaryRepeatableItem {
  /**
   * heading field in *Disclaimer → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.repeatable[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Disclaimer → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.repeatable[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Disclaimer → Default → Primary*
 */
export interface DisclaimerSliceDefaultPrimary {
  /**
   * Non Repeated field in *Disclaimer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.non_repeated[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  non_repeated: prismic.GroupField<
    Simplify<DisclaimerSliceDefaultPrimaryNonRepeatedItem>
  >;

  /**
   * Repeatable field in *Disclaimer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.repeatable[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeatable: prismic.GroupField<
    Simplify<DisclaimerSliceDefaultPrimaryRepeatableItem>
  >;
}

/**
 * Default variation for Disclaimer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DisclaimerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DisclaimerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Disclaimer*
 */
type DisclaimerSliceVariation = DisclaimerSliceDefault;

/**
 * Disclaimer Shared Slice
 *
 * - **API ID**: `disclaimer`
 * - **Description**: Disclaimer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DisclaimerSlice = prismic.SharedSlice<
  "disclaimer",
  DisclaimerSliceVariation
>;

/**
 * Item in *CadService → Default → Primary → card*
 */
export interface EngineeringServiceSliceDefaultPrimaryCardItem {
  /**
   * card image field in *CadService → Default → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: engineering_service.default.primary.card[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card heading field in *CadService → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engineering_service.default.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card link field in *CadService → Default → Primary → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: engineering_service.default.primary.card[].card_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * card points field in *CadService → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engineering_service.default.primary.card[].card_points
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_points: prismic.RichTextField;
}

/**
 * Primary content in *CadService → Default → Primary*
 */
export interface EngineeringServiceSliceDefaultPrimary {
  /**
   * Heading field in *CadService → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engineering_service.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * card field in *CadService → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: engineering_service.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<
    Simplify<EngineeringServiceSliceDefaultPrimaryCardItem>
  >;

  /**
   * Background Image field in *CadService → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: engineering_service.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for CadService Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EngineeringServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EngineeringServiceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CadService*
 */
type EngineeringServiceSliceVariation = EngineeringServiceSliceDefault;

/**
 * CadService Shared Slice
 *
 * - **API ID**: `engineering_service`
 * - **Description**: EngineeringService
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EngineeringServiceSlice = prismic.SharedSlice<
  "engineering_service",
  EngineeringServiceSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → faq*
 */
export interface FaqSliceDefaultPrimaryFaqItem {
  /**
   * question field in *Faq → Default → Primary → faq*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faq[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * answer field in *Faq → Default → Primary → faq*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faq[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * heading field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * faq field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faq[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryFaqItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *FooterTixasLogo → Default → Primary*
 */
export interface FooterTixasSliceDefaultPrimary {
  /**
   * tixas_footer field in *FooterTixasLogo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_tixas.default.primary.tixas_footer
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tixas_footer: prismic.ImageField<never>;
}

/**
 * Default variation for FooterTixasLogo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterTixasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterTixasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterTixasLogo*
 */
type FooterTixasSliceVariation = FooterTixasSliceDefault;

/**
 * FooterTixasLogo Shared Slice
 *
 * - **API ID**: `footer_tixas`
 * - **Description**: FooterTixas
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterTixasSlice = prismic.SharedSlice<
  "footer_tixas",
  FooterTixasSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Hexa Grid*
 */
export interface HeroSliceDefaultPrimaryHexaGridItem {
  /**
   * Hexa Image field in *Hero → Default → Primary → Hexa Grid*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hexa_grid[].hexa_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hexa_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * contant field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.contant
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contant: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Sub Headeing field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_headeing: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Hexa Grid field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hexa_grid[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hexa_grid: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryHexaGridItem>>;

  /**
   * Header Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.header_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *IndustrialCae → Default → Primary → cards*
 */
export interface IndustrialCaeSliceDefaultPrimaryCardsItem {
  /**
   * card image field in *IndustrialCae → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.cards[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card link field in *IndustrialCae → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.cards[].card_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_link: prismic.KeyTextField;

  /**
   * card points field in *IndustrialCae → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.cards[].card_points
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_points: prismic.RichTextField;

  /**
   * card heading field in *IndustrialCae → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.cards[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;
}

/**
 * Primary content in *IndustrialCae → Default → Primary*
 */
export interface IndustrialCaeSliceDefaultPrimary {
  /**
   * cards field in *IndustrialCae → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<IndustrialCaeSliceDefaultPrimaryCardsItem>
  >;

  /**
   * Backgroung Image field in *IndustrialCae → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.backgroung_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroung_image: prismic.ImageField<never>;

  /**
   * sub heading field in *IndustrialCae → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * heading field in *IndustrialCae → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industrial_cae.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for IndustrialCae Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustrialCaeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IndustrialCaeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IndustrialCae*
 */
type IndustrialCaeSliceVariation = IndustrialCaeSliceDefault;

/**
 * IndustrialCae Shared Slice
 *
 * - **API ID**: `industrial_cae`
 * - **Description**: IndustrialCae
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustrialCaeSlice = prismic.SharedSlice<
  "industrial_cae",
  IndustrialCaeSliceVariation
>;

/**
 * Item in *InformationObligations → Default → Primary → Non Repeated*
 */
export interface InformationObligationsSliceDefaultPrimaryNonRepeatedItem {
  /**
   * heading field in *InformationObligations → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_obligations.default.primary.non_repeated[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * contant field in *InformationObligations → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_obligations.default.primary.non_repeated[].contant
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contant: prismic.RichTextField;
}

/**
 * Item in *InformationObligations → Default → Primary → Repeatable*
 */
export interface InformationObligationsSliceDefaultPrimaryRepeatableItem {
  /**
   * heading field in *InformationObligations → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_obligations.default.primary.repeatable[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *InformationObligations → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_obligations.default.primary.repeatable[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *InformationObligations → Default → Primary*
 */
export interface InformationObligationsSliceDefaultPrimary {
  /**
   * Non Repeated field in *InformationObligations → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: information_obligations.default.primary.non_repeated[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  non_repeated: prismic.GroupField<
    Simplify<InformationObligationsSliceDefaultPrimaryNonRepeatedItem>
  >;

  /**
   * Repeatable field in *InformationObligations → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: information_obligations.default.primary.repeatable[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeatable: prismic.GroupField<
    Simplify<InformationObligationsSliceDefaultPrimaryRepeatableItem>
  >;
}

/**
 * Default variation for InformationObligations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InformationObligationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InformationObligationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InformationObligations*
 */
type InformationObligationsSliceVariation = InformationObligationsSliceDefault;

/**
 * InformationObligations Shared Slice
 *
 * - **API ID**: `information_obligations`
 * - **Description**: InformationObligations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InformationObligationsSlice = prismic.SharedSlice<
  "information_obligations",
  InformationObligationsSliceVariation
>;

/**
 * Item in *Location → Default → Primary → location card*
 */
export interface LocationSliceDefaultPrimaryLocationCardItem {
  /**
   * Title field in *Location → Default → Primary → location card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_card[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Place field in *Location → Default → Primary → location card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_card[].place
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  place: prismic.KeyTextField;

  /**
   * longitude latitude field in *Location → Default → Primary → location card*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_card[].longitude_latitude
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  longitude_latitude: prismic.GeoPointField;
}

/**
 * Primary content in *Location → Default → Primary*
 */
export interface LocationSliceDefaultPrimary {
  /**
   * Heading field in *Location → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Location → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_headeing: prismic.RichTextField;

  /**
   * location card field in *Location → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  location_card: prismic.GroupField<
    Simplify<LocationSliceDefaultPrimaryLocationCardItem>
  >;

  /**
   * contant field in *Location → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.contant
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contant: prismic.RichTextField;
}

/**
 * Default variation for Location Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Location*
 */
type LocationSliceVariation = LocationSliceDefault;

/**
 * Location Shared Slice
 *
 * - **API ID**: `location`
 * - **Description**: Location
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationSlice = prismic.SharedSlice<
  "location",
  LocationSliceVariation
>;

/**
 * Item in *Partners → Default → Primary → Partners card*
 */
export interface PartnersSliceDefaultPrimaryPartnersCardItem {
  /**
   * card image field in *Partners → Default → Primary → Partners card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.partners_card[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card link field in *Partners → Default → Primary → Partners card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.partners_card[].card_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Partners → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Heading field in *Partners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Partners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_headeing: prismic.RichTextField;

  /**
   * Partners card field in *Partners → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.partners_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  partners_card: prismic.GroupField<
    Simplify<PartnersSliceDefaultPrimaryPartnersCardItem>
  >;

  /**
   * Contact field in *Partners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.contact
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact: prismic.RichTextField;
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Item in *PrivacyPolicy → Default → Primary → Repeatable*
 */
export interface PrivacyPolicySliceDefaultPrimaryRepeatableItem {
  /**
   * heading field in *PrivacyPolicy → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.default.primary.repeatable[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *PrivacyPolicy → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.default.primary.repeatable[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Item in *PrivacyPolicy → Default → Primary → Non Repeated*
 */
export interface PrivacyPolicySliceDefaultPrimaryNonRepeatedItem {
  /**
   * heading field in *PrivacyPolicy → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.default.primary.non_repeated[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * contant field in *PrivacyPolicy → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.default.primary.non_repeated[].contant
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contant: prismic.RichTextField;
}

/**
 * Primary content in *PrivacyPolicy → Default → Primary*
 */
export interface PrivacyPolicySliceDefaultPrimary {
  /**
   * Repeatable field in *PrivacyPolicy → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.default.primary.repeatable[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeatable: prismic.GroupField<
    Simplify<PrivacyPolicySliceDefaultPrimaryRepeatableItem>
  >;

  /**
   * Non Repeated field in *PrivacyPolicy → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.default.primary.non_repeated[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  non_repeated: prismic.GroupField<
    Simplify<PrivacyPolicySliceDefaultPrimaryNonRepeatedItem>
  >;
}

/**
 * Default variation for PrivacyPolicy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrivacyPolicySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivacyPolicySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivacyPolicy*
 */
type PrivacyPolicySliceVariation = PrivacyPolicySliceDefault;

/**
 * PrivacyPolicy Shared Slice
 *
 * - **API ID**: `privacy_policy`
 * - **Description**: PrivacyPolicy
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrivacyPolicySlice = prismic.SharedSlice<
  "privacy_policy",
  PrivacyPolicySliceVariation
>;

/**
 * Item in *Services → Default → Primary → card*
 */
export interface ServicesSliceDefaultPrimaryCardItem {
  /**
   * card image field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card link field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * card heading field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card sub heading field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_sub_heading: prismic.RichTextField;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * lable field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.lable
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lable: prismic.RichTextField;

  /**
   * description field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * card field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<ServicesSliceDefaultPrimaryCardItem>>;

  /**
   * span lable field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.span_lable
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  span_lable: prismic.KeyTextField;

  /**
   * ISO image field in *Services → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.iso_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  iso_image: prismic.ImageField<never>;

  /**
   * QR Code field in *Services → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.qr_code
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  qr_code: prismic.ImageField<never>;

  /**
   * iso label field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.iso_label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  iso_label: prismic.RichTextField;

  /**
   * iso license field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.iso_license
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  iso_license: prismic.RichTextField;

  /**
   * TIXAS image field in *Services → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.tixas_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tixas_image: prismic.ImageField<never>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Item in *Team → Default → Primary → team card*
 */
export interface TeamSliceDefaultPrimaryTeamCardItem {
  /**
   * person image field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].person_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  person_image: prismic.ImageField<never>;

  /**
   * Name field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * desigation field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].desigation
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  desigation: prismic.RichTextField;

  /**
   * feild field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].feild
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feild: prismic.RichTextField;

  /**
   * description field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * card link field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].card_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Heading field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_headeing: prismic.RichTextField;

  /**
   * contact field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.contact
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact: prismic.RichTextField;

  /**
   * team card field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  team_card: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryTeamCardItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *TermAndCondtion → Default → Primary → Non Repeated*
 */
export interface TermAndCondtionSliceDefaultPrimaryNonRepeatedItem {
  /**
   * heading field in *TermAndCondtion → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: term_and_condtion.default.primary.non_repeated[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * contant field in *TermAndCondtion → Default → Primary → Non Repeated*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: term_and_condtion.default.primary.non_repeated[].contant
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contant: prismic.RichTextField;
}

/**
 * Item in *TermAndCondtion → Default → Primary → Repeatable*
 */
export interface TermAndCondtionSliceDefaultPrimaryRepeatableItem {
  /**
   * heading field in *TermAndCondtion → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: term_and_condtion.default.primary.repeatable[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *TermAndCondtion → Default → Primary → Repeatable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: term_and_condtion.default.primary.repeatable[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *TermAndCondtion → Default → Primary*
 */
export interface TermAndCondtionSliceDefaultPrimary {
  /**
   * Non Repeated field in *TermAndCondtion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: term_and_condtion.default.primary.non_repeated[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  non_repeated: prismic.GroupField<
    Simplify<TermAndCondtionSliceDefaultPrimaryNonRepeatedItem>
  >;

  /**
   * Repeatable field in *TermAndCondtion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: term_and_condtion.default.primary.repeatable[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeatable: prismic.GroupField<
    Simplify<TermAndCondtionSliceDefaultPrimaryRepeatableItem>
  >;
}

/**
 * Default variation for TermAndCondtion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TermAndCondtionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TermAndCondtionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TermAndCondtion*
 */
type TermAndCondtionSliceVariation = TermAndCondtionSliceDefault;

/**
 * TermAndCondtion Shared Slice
 *
 * - **API ID**: `term_and_condtion`
 * - **Description**: TermAndCondtion
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TermAndCondtionSlice = prismic.SharedSlice<
  "term_and_condtion",
  TermAndCondtionSliceVariation
>;

/**
 * Item in *Header → Default → Primary → Navbar*
 */
export interface TopNavbarSliceDefaultPrimaryNavbarItem {
  /**
   * Link field in *Header → Default → Primary → Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.navbar[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Header → Default → Primary → service sub menu*
 */
export interface TopNavbarSliceDefaultPrimaryServiceSubMenuItem {
  /**
   * link field in *Header → Default → Primary → service sub menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.service_sub_menu[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface TopNavbarSliceDefaultPrimary {
  /**
   * Logo field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navbar field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.navbar[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navbar: prismic.GroupField<Simplify<TopNavbarSliceDefaultPrimaryNavbarItem>>;

  /**
   * service sub menu field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.service_sub_menu[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  service_sub_menu: prismic.GroupField<
    Simplify<TopNavbarSliceDefaultPrimaryServiceSubMenuItem>
  >;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TopNavbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TopNavbarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type TopNavbarSliceVariation = TopNavbarSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `top_navbar`
 * - **Description**: TopNavbar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TopNavbarSlice = prismic.SharedSlice<
  "top_navbar",
  TopNavbarSliceVariation
>;

/**
 * Item in *Vacencies → Default → Primary → vacency card*
 */
export interface VacenciesSliceDefaultPrimaryVacencyCardItem {
  /**
   * card image field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card heading field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card Button field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Card Sub heading field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_sub_heading: prismic.KeyTextField;

  /**
   * card label field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_label: prismic.KeyTextField;
}

/**
 * Primary content in *Vacencies → Default → Primary*
 */
export interface VacenciesSliceDefaultPrimary {
  /**
   * Heading field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_headeing: prismic.RichTextField;

  /**
   * vacency card field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  vacency_card: prismic.GroupField<
    Simplify<VacenciesSliceDefaultPrimaryVacencyCardItem>
  >;

  /**
   * Conatct field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.conatct
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  conatct: prismic.RichTextField;

  /**
   * Is_vacancies field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: vacencies.default.primary.is_vacancies
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_vacancies: prismic.BooleanField;

  /**
   * no vacancies label field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.no_vacancies_label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  no_vacancies_label: prismic.RichTextField;

  /**
   * sub title field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_title: prismic.RichTextField;
}

/**
 * Default variation for Vacencies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VacenciesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VacenciesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vacencies*
 */
type VacenciesSliceVariation = VacenciesSliceDefault;

/**
 * Vacencies Shared Slice
 *
 * - **API ID**: `vacencies`
 * - **Description**: Vacencies
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VacenciesSlice = prismic.SharedSlice<
  "vacencies",
  VacenciesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavbarItem,
      HeaderDocumentDataServiceSubMenuItem,
      HeaderDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataFooterLinkItem,
      SettingsDocumentDataFooterIconItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AutomotiveServicesSlice,
      AutomotiveServicesSliceDefaultPrimaryCardItem,
      AutomotiveServicesSliceDefaultPrimary,
      AutomotiveServicesSliceVariation,
      AutomotiveServicesSliceDefault,
      CaeServiceSlice,
      CaeServiceSliceDefaultPrimaryCardItem,
      CaeServiceSliceDefaultPrimary,
      CaeServiceSliceVariation,
      CaeServiceSliceDefault,
      CooperateLinkSlice,
      CooperateLinkSliceDefaultPrimaryCooperateLinksItem,
      CooperateLinkSliceDefaultPrimary,
      CooperateLinkSliceVariation,
      CooperateLinkSliceDefault,
      DisclaimerSlice,
      DisclaimerSliceDefaultPrimaryNonRepeatedItem,
      DisclaimerSliceDefaultPrimaryRepeatableItem,
      DisclaimerSliceDefaultPrimary,
      DisclaimerSliceVariation,
      DisclaimerSliceDefault,
      EngineeringServiceSlice,
      EngineeringServiceSliceDefaultPrimaryCardItem,
      EngineeringServiceSliceDefaultPrimary,
      EngineeringServiceSliceVariation,
      EngineeringServiceSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryFaqItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      FooterTixasSlice,
      FooterTixasSliceDefaultPrimary,
      FooterTixasSliceVariation,
      FooterTixasSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryHexaGridItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      IndustrialCaeSlice,
      IndustrialCaeSliceDefaultPrimaryCardsItem,
      IndustrialCaeSliceDefaultPrimary,
      IndustrialCaeSliceVariation,
      IndustrialCaeSliceDefault,
      InformationObligationsSlice,
      InformationObligationsSliceDefaultPrimaryNonRepeatedItem,
      InformationObligationsSliceDefaultPrimaryRepeatableItem,
      InformationObligationsSliceDefaultPrimary,
      InformationObligationsSliceVariation,
      InformationObligationsSliceDefault,
      LocationSlice,
      LocationSliceDefaultPrimaryLocationCardItem,
      LocationSliceDefaultPrimary,
      LocationSliceVariation,
      LocationSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimaryPartnersCardItem,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      PrivacyPolicySlice,
      PrivacyPolicySliceDefaultPrimaryRepeatableItem,
      PrivacyPolicySliceDefaultPrimaryNonRepeatedItem,
      PrivacyPolicySliceDefaultPrimary,
      PrivacyPolicySliceVariation,
      PrivacyPolicySliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryCardItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryTeamCardItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TermAndCondtionSlice,
      TermAndCondtionSliceDefaultPrimaryNonRepeatedItem,
      TermAndCondtionSliceDefaultPrimaryRepeatableItem,
      TermAndCondtionSliceDefaultPrimary,
      TermAndCondtionSliceVariation,
      TermAndCondtionSliceDefault,
      TopNavbarSlice,
      TopNavbarSliceDefaultPrimaryNavbarItem,
      TopNavbarSliceDefaultPrimaryServiceSubMenuItem,
      TopNavbarSliceDefaultPrimary,
      TopNavbarSliceVariation,
      TopNavbarSliceDefault,
      VacenciesSlice,
      VacenciesSliceDefaultPrimaryVacencyCardItem,
      VacenciesSliceDefaultPrimary,
      VacenciesSliceVariation,
      VacenciesSliceDefault,
    };
  }
}
