import type { Metadata } from "next";
import "./globals.css"; 
import Header from "../components/Header";
import Footer from "../components/Footer";
import AOSInitializer from "../components/AOSInitializer";
import "aos/dist/aos.css"; 
import { montserrat, roboto } from "./font";

export const metadata: Metadata = {
  title: "Jn-consulting",
  description: "Generated by Joseph & Nouman",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={`${roboto.className}  ${montserrat.className} antialiased`} 
      >
        <AOSInitializer />
        {children}
      </body>
    </html>
  );
}