// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  automotive_services: dynamic(() => import("./PageServices")),
  cae_service: dynamic(() => import("./CaeService")),
  cooperate_link: dynamic(() => import("./CooperateLink")),
  engineering_service: dynamic(() => import("./CadService")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  location: dynamic(() => import("./Location")),
  partners: dynamic(() => import("./Partners")),
  privacy_policy: dynamic(() => import("./PrivacyPolicy")),
  services: dynamic(() => import("./Services")),
  team: dynamic(() => import("./Team")),
  term_and_condtion: dynamic(() => import("./TermAndCondtion")),
  top_navbar: dynamic(() => import("./Header")),
  vacencies: dynamic(() => import("./Vacencies")),
};
